@startditaa
                                  calling order
      ------------------------------------------------------------------>

+-----------+   +------------+    +----------+   +-------------+   +-----------+
|           |   |            |    |          |   |             |   |           |
|   Input   |   | Powertrain |    | Steering |   | DummySensor |   | Dashboard |
|  manager  |   |            |    |          |   |             |   |           |
|           |   |            |    |          |   |             |   |           |
+-----+-----+   +---+----+---+    +---+---+--+   +----+---+----+   +-----+-----+
      |             ^    |            ^   |           ^   |              ^
      |             |    |            |   |           |   |              |
      v             |    v            |   v           |   v              |
+-----+-------------+----+------------+---+-----------+---+--------------+-----+
|                              VirtualFunctionBus                              |
+------------------------------------------------------------------------------+
@endditaa
