@startditaa
                        calling order
      -------------------------------------------------->

+-----------+   +------------+    +----------+   +-------------+
|           |   |            |    |          |   |             |
|   Input   |   | Powertrain |    | Steering |   | DummySensor |
|  manager  |   |            |    |          |   |             |
|           |   |            |    |          |   |             |
+-----+-----+   +---+----+---+    +---+---+--+   +----+---+----+
      |             ^    |            ^   |           ^   |
      |             |    |            |   |           |   |
      v             |    v            |   v           |   v
+-----+-------------+----+------------+---+-----------+---+----+
|                       VirtualFunctionBus                     |
+--------------------------------------------------------------+
@endditaa
